const mix = require('laravel-mix');

mix.sass('resources/assets/sass/app.scss', 'public/css')
   .js('resources/assets/js/app.js', 'public/js')
   .styles(
    [
        './node_modules/toastr/toastr.scss',
        './node_modules/bootstrap-social/bootstrap-social.css'
    ],
    'public/css/main.css')
    .styles(
    [
        './vendor/haifahrul/template-eshopper/css/bootstrap.min.css',
        './vendor/haifahrul/template-eshopper/css/font-awesome.min.css',
        './vendor/haifahrul/template-eshopper/css/animate.css',
        './vendor/haifahrul/template-eshopper/css/prettyPhoto.css',
        './vendor/haifahrul/template-eshopper/css/price-range.css',
        './vendor/haifahrul/template-eshopper/css/main.css',
        './vendor/haifahrul/template-eshopper/css/responsive.css'
    ],
    'public/css/eshopper.css')
    .scripts(
    [
        './node_modules/jquery/dist/jquery.js',
        './node_modules/bootstrap-sass/assets/javascripts/bootstrap.js',
        './node_modules/toastr/toastr.js'
    ],
    'public/js/main.js')
    .scripts(
    [
        './vendor/haifahrul/template-eshopper/js/jquery.scrollUp.min.js',
        './vendor/haifahrul/template-eshopper/js/price-range.js',
        './vendor/haifahrul/template-eshopper/js/jquery.prettyPhoto.js',
        './vendor/haifahrul/template-eshopper/js/main.js'
    ],
    'public/js/eshopper.js')
    .scripts(
    [
        'resources/assets/js/custom.js'
    ],
    'public/js/custom.js')
    .copy(
    [
        'node_modules/font-awesome/fonts/',
        'node_modules/bootstrap-sass/assets/fonts/'
    ],
    'public/fonts/')
    .copy(
        [
            'vendor/haifahrul/template-eshopper/images/'
        ],
        'public/images/'
   );